In [2]:
spam_amount = 0
print(spam_amount)

# Ordering Spam, egg, Spam, Spam, bacon and Spam (4 more servings of Spam)
spam_amount = spam_amount + 4

if spam_amount > 0:
    print("But I don't want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song)

0
But I don't want ANY spam!
Spam Spam Spam Spam 


Function calls - We call functions by putting parentheses after their name, and putting the inputs (or arguments) to the function in those parentheses.

In [6]:
type(spam_amount)

int

In [7]:
type(20.22)

float

In [9]:
#normal division
print(5 / 2)
print(6 / 2)

2.5
3.0


In [11]:
#floor division
print(5 // 2)
print(6 // 2)

2
3


Order of operations - PEMDAS (P>E>M/D>A/S)

##### Builtin functions for working with numbers

In [15]:
print(min(1, 2, 3))
print(max(1, 2, 3))
print(abs(32))
print(abs(-32))
print(float(10))
print(int(3.33))
#called on strings
print(int('807') + 1)

1
3
32
32
10.0
3
808


In [27]:
round(178.12345, ndigits=-1)

180.0

In [29]:
import sys
sys.stdout.write('text')

text

In [33]:
print(1,2,3,sep='-')
print(4,5,6,sep='-')

1-2-3
4-5-6


In [34]:
print()

In [36]:
def can_run_for_president(age, is_natural_born_citizen):
    """Can someone of the given age and citizenship status run for president in the US?"""
    # The US Constitution says you must be a natural born citizen *and* at least 35 years old
    return is_natural_born_citizen and (age >= 35)

In [37]:
can_run_for_president(40, True)

True

In [39]:
def can_run_for_president(age, is_natural_born_citizen):
    """Can someone of the given age and citizenship status run for president in the US?"""
    a= (is_natural_born_citizen==True)
    b= (age >= 35)
    return a and b

In [42]:
can_run_for_president(40, True)

True

In [48]:
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
        print("Always printed, regardless of x's value; x =", x)


In [49]:
f(1)

Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1


In [53]:
#f(0)
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)
f(0)

Always printed, regardless of x's value; x = 0


In [55]:
print(bool(""))
print(bool(" "))

False
True


In [57]:
hands = [
    ['J', 'Q', 'K'],
    ['2', '2', '2'],
    ['6', 'A', 'K'], # (Comma after the last element is optional)
]

In [62]:
type(hands)

list

In [63]:
hands

[['J', 'Q', 'K'], ['2', '2', '2'], ['6', 'A', 'K']]

In [64]:
print(hands)

[['J', 'Q', 'K'], ['2', '2', '2'], ['6', 'A', 'K']]


In [67]:
import pandas as pd
pd.DataFrame(hands)

0  1  2
0  J  Q  K
1  2  2  2
2  6  A  K

In [68]:
sorted(hands)

[['2', '2', '2'], ['6', 'A', 'K'], ['J', 'Q', 'K']]

In [74]:
tst = [
    [5,6,2],
    [1,8,9],
    [8,6,3] # (Comma after the last element is optional)
]

In [75]:
sorted(tst)

[[1, 8, 9], [5, 6, 2], [8, 6, 3]]

In [81]:
tst = [5,6,4]

In [82]:
sum(tst)

15

In [301]:
tst = [
    [5,6,2],
    [1,8,9],
    [8,6,3] # (Comma after the last element is optional)
]

In [302]:
type(tst)

list

In [88]:
tst.pop()

[8, 6, 3]

In [89]:
tst

[[5, 6, 2], [1, 8, 9]]

In [91]:
tst.index([1, 8, 9])

1

In [92]:
[1, 8, 9] in tst

True

In [93]:
tst.count([1, 8, 9])

1

In [99]:
tst.pop(1)

[1, 8, 9]

In [100]:
tst

[[5, 6, 2]]

In [101]:
x=0.125
x.as_integer_ratio()

(1, 8)

In [102]:
num,denom=x.as_integer_ratio()

In [105]:
print(num)
print(denom)

1
8


In [106]:
l=[1,2,3]

In [107]:
l[1]

2

In [108]:
a=l[1]
a

2

In [109]:
help(l)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [110]:
def purple_shell(racers):
    """Given a list of racers, set the first place racer (at the front of the list) to last
    place and vice versa.
    
    >>> r = ["Mario", "Bowser", "Luigi"]
    >>> purple_shell(r)
    >>> r
    ["Luigi", "Bowser", "Mario"]
    """
    f=racers[0]
    racers[0]=racers[-1]
    racers[-1]=f
    #return racers
    pass

In [112]:
r = ["Mario", "Bowser", "Luigi"]
purple_shell(r)
r

['Luigi', 'Bowser', 'Mario']

In [113]:
c = []
len(c)

0

In [114]:
d = [1, 2, 3][1:]

In [115]:
d

[2, 3]

In [116]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ')

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [117]:
for i in planets:
    print(i)

Mercury
Venus
Earth
Mars
Jupiter
Saturn
Uranus
Neptune


In [119]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [122]:
multiplicands = (2, 2, 2, 3, 3, 5)
product=1
for i in multiplicands:
    product=product*i
print(product)

360


In [123]:
multiplicands = (2, 2, 2, 3, 3, 5)
product=1
for i in multiplicands:
    product=product*i
    print(product)

2
4
8
24
72
360


In [124]:
multiplicands = (2, 3, 4, 5, 6)
product=1
for i in multiplicands:
    product=product*i
    print(product)

2
6
24
120
720


In [125]:
range(5)

range(0, 5)

In [126]:
print(range(5))

range(0, 5)


In [128]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [129]:
loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6]
loud_short_planets

['VENUS!', 'EARTH!', 'MARS!']

In [131]:
[32 for planet in planets]

[32, 32, 32, 32, 32, 32, 32, 32]

In [136]:
#count the number of negative numbers in a list
def count_neg(num):
    count = 0
    for i in num:
        if i < 0:
            count = count+1
    return count

In [137]:
count_neg([1,-2,-3,5,5])

2

In [143]:
#using list comprehension
def neg(num):
    return len([i for i in num if i < 0])
    


In [144]:
neg([1,-2,-3,5,5])

2

In [146]:
sum([1,1,1,1])

4

In [147]:
sum([True,True,False])

2

In [154]:
'Pluto\'s a planet!'

"Pluto's a planet!"

In [155]:
planet="Mercury"

In [158]:
[i+'!' for i in planet]

['M!', 'e!', 'r!', 'c!', 'u!', 'r!', 'y!']

In [161]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [171]:
width=10
fillchar='@'
planet.center(width,fillchar)

'@Mercury@@'

In [173]:
planet='pluto'
planet.index('uto')

2

In [183]:
test='pluto is a planet'
planets='tre'
test.startswith(planet)

True

In [185]:
date='1900-01-02'
date.split('-')

['1900', '01', '02']

In [187]:
year,month,day=date.split('-')
print(year)
print(month)
print(day)

1900
01
02


In [192]:
'/'.join([month, day, year])

'01/02/1900'

In [193]:
numbers = {'one':1, 'two':2, 'three':3}

In [194]:
numbers

{'one': 1, 'two': 2, 'three': 3}

In [198]:
numbers = {'one':1,
           'two':2,
           'three':3}
numbers['one']

1

In [205]:
planet=['Mercury','Venus','Earth']
planet_dict = {
                i:i[0] 
               for i in planet
              }


In [211]:
planet_dict

{'Mercury': 'M', 'Venus': 'V', 'Earth': 'E'}

In [212]:
planet_dict.items()

dict_items([('Mercury', 'M'), ('Venus', 'V'), ('Earth', 'E')])

In [214]:
planet_dict.values()

dict_values(['M', 'V', 'E'])

In [222]:
planet_dict.items()

dict_items([('Mercury', 'M'), ('Venus', 'V'), ('Earth', 'E')])

In [216]:
type(planet_dict.values())

dict_values

In [220]:
for i,j in planet_dict.items():
    print(i +' begin with '+j)

Mercury begin with M
Venus begin with V
Earth begin with E


In [221]:
for i,j in planet_dict.items():
    print("{} begin with {}".format(i,j))

Mercury begin with M
Venus begin with V
Earth begin with E


In [224]:
l='\n'
len(l)

1

In [225]:
l

'\n'

In [227]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
a=enumerate(doc_list)

In [239]:
 for i, doc in enumerate(doc_list):
        print(i,doc)
        tokens = doc.split()
        print(tokens)
        normalized = [token.rstrip('.,').lower() for token in tokens]
        print(normalized)
        indices = [] 
        if 'casino'.lower() in normalized:
            indices.append(i)
            print(indices)

0 The Learn Python Challenge Casino.
['The', 'Learn', 'Python', 'Challenge', 'Casino.']
['the', 'learn', 'python', 'challenge', 'casino']
[0]
1 They bought a car
['They', 'bought', 'a', 'car']
['they', 'bought', 'a', 'car']
2 Casinoville
['Casinoville']
['casinoville']


In [254]:
doc_list = ["The Learn Python Challenge Casino.", "They bought casino car", "Casinoville"]
search='casino'
for i,j in enumerate(doc_list):
    print(i,j)
    test=[]
    name_list=j.split()
    print(name_list)
    lower_name_list=[i.lower().rstrip('.,') for i in name_list]
    print(lower_name_list)
    for i in lower_name_list:
        if i == search.lower():
            test.append(lower_name_list.index(i))
            print(test)
    

0 The Learn Python Challenge Casino.
['The', 'Learn', 'Python', 'Challenge', 'Casino.']
['the', 'learn', 'python', 'challenge', 'casino']
[4]
1 They bought casino car
['They', 'bought', 'casino', 'car']
['they', 'bought', 'casino', 'car']
[2]
2 Casinoville
['Casinoville']
['casinoville']


In [262]:
doc_list = ["The Learn Python Challenge Casino.", "They bought casino car", "Casinoville"]
search='casino'

for i,j in enumerate(doc_list):
    print(i,j)
    test=[]
    name_list=j.split()
    print(name_list)
    lower_name_list=[i.lower().rstrip('.,') for i in name_list]
    print(lower_name_list)
    if search.lower() in lower_name_list:
        test.append(i)
        print(test)
    

0 The Learn Python Challenge Casino.
['The', 'Learn', 'Python', 'Challenge', 'Casino.']
['the', 'learn', 'python', 'challenge', 'casino']
[0]
1 They bought casino car
['They', 'bought', 'casino', 'car']
['they', 'bought', 'casino', 'car']
[1]
2 Casinoville
['Casinoville']
['casinoville']


In [270]:

def word_search(doc_list, keyword):
    test=[]
    for i,j in enumerate(doc_list):
    ##print(i,j)
        
        name_list=j.split()
    ##print(name_list)
        lower_name_list=[i.lower().rstrip('.,') for i in name_list]
    ##print(lower_name_list)
        if keyword.lower() in lower_name_list:
            test.append(i)
        ##print(test)
    return test  


In [273]:
doc_list = ["The Learn Python Challenge Casino.", "They bought casino car", "Casinoville","movies", "casino,."]
keyword = 'casino'
word_search(doc_list, keyword)

[0, 1, 4]

In [275]:
import math
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [279]:
math.log(100,10)

2.0

In [278]:
math.log(1)

0.0

In [280]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.
   

In [285]:
import numpy
rolls = numpy.random.randint(low=1, high=6, size=10)
print(type(rolls))
rolls

<class 'numpy.ndarray'>


array([2, 2, 5, 1, 2, 5, 2, 2, 1, 1])

In [286]:
type(numpy)

module

In [287]:
type(numpy.random)

module

In [288]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [289]:
dir(numpy.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bit_generator',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',

In [296]:
roll = numpy.random.randint(low=1,high=6,size=10)
roll

array([4, 5, 4, 3, 1, 2, 2, 2, 4, 2])

In [293]:
help(numpy.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

In [297]:
rolls

array([2, 2, 5, 1, 2, 5, 2, 2, 1, 1])

In [298]:
rolls+10

array([12, 12, 15, 11, 12, 15, 12, 12, 11, 11])

In [299]:
rolls>10

array([False, False, False, False, False, False, False, False, False,
       False])

In [303]:
xlist = [[1,1,2]
        ,[2,3,4]]

In [305]:
xlist

[[1, 1, 2], [2, 3, 4]]

In [306]:
type(xlist)

list

In [309]:
a=numpy.asarray(xlist)
a

array([[1, 1, 2],
       [2, 3, 4]])

In [310]:
a[1,1]

3

In [312]:
a[1,-1]

4

In [313]:
xlist

[[1, 1, 2], [2, 3, 4]]

In [315]:
xlist[1][1]

3

In [316]:
hand1 = BlackjackHand(['K', 'A'])
hand2 = BlackjackHand(['7', '10', 'A'])

NameError: name 'BlackjackHand' is not defined

In [ ]:
def blackjack_hand_greater_than(hand_1, hand_2):
    for i in hand_1
    """
    Return True if hand_1 beats hand_2, and False otherwise.
    
    In order for hand_1 to beat hand_2 the following must be true:
    - The total of hand_1 must not exceed 21
    - The total of hand_1 must exceed the total of hand_2 OR hand_2's total must exceed 21
    
    Hands are represented as a list of cards. Each card is represented by a string.
    
    When adding up a hand's total, cards with numbers count for that many points. Face
    cards ('J', 'Q', and 'K') are worth 10 points. 'A' can count for 1 or 11.
    
    When determining a hand's total, you should try to count aces in the way that 
    maximizes the hand's total without going over 21. e.g. the total of ['A', 'A', '9'] is 21,
    the total of ['A', 'A', '9', '3'] is 14.
    
    Examples:
    >>> blackjack_hand_greater_than(['K'], ['3', '4'])
    True
    >>> blackjack_hand_greater_than(['K'], ['10'])
    False
    >>> blackjack_hand_greater_than(['K', 'K', '2'], ['3'])
    False
    """

In [347]:
def blackjack_hand_greater_than(hand_1, hand_2):
    a = 0
    b = 0
    for i in hand_1:
        if i == 'K' or i == 'Q' or i == 'J' :
            i = 10
        elif i == 'A':
            i = 1
        else:
            i
        a=a+int(i)
        #print(a)
    for j in hand_2:
        if j == 'K' or j == 'Q' or j == 'J' :
            j = 10
        elif i == 'A':
            i = 1
        else:
            j
        b=b+int(j)
        #print(b)
    while a
    if a <= 21 and (a>b or b > 21):
        return True
    else:
        return False


In [336]:
a = '3'
type(a)
if type(a)==str:
    print(True)

True


In [348]:
blackjack_hand_greater_than(['K', 'K', '2'], ['3'])

False

In [371]:
#hand_1 = ['A', '3', '2']
total = 0
a = 0
for i in hand_1:
    if i == 'K' or i == 'Q' or i == 'J' :
        total += 10
    elif i == 'A':
        a += 1
    else:
        total += int(i)  
total+=a
print(total)
while total+10 <= 21 and a > 0:
    total+=10
    #a-=1
total

6


16

In [ ]:
total = 0
    # Count the number of aces and deal with how to apply them at the end.
aces = 0
for card in hand:
        if card in ['J', 'Q', 'K']:
            total += 10
        elif card == 'A':
            aces += 1
        else:
            # Convert number cards (e.g. '7') to ints
            total += int(card)

In [376]:
def hand_total(hand_1):
    total = 0
    a = 0
    for i in hand_1:
        if i == 'K' or i == 'Q' or i == 'J' :
            total += 10
        elif i == 'A':
            a += 1
        else:
            total += int(i)  
    total+=a
    #print(total)
    while total+10 <= 21 and a > 0:
        total+=10
        #a-=1
    return total

In [377]:
def blackjack_hand_greater_than(hand_1, hand_2):
    total_1 = hand_total(hand_1)
    total_2 = hand_total(hand_2)
    return total_1 <= 21 and (total_1 > total_2 or total_2 > 21)

In [381]:
#blackjack_hand_greater_than(['K', 'K', '2'], ['3'])
blackjack_hand_greater_than(['A', 'A', '2'], ['3'])

True

In [399]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
for doc in doc_list:
    count=0
    print(doc.split())
    word_list = doc.split()
    for word in word_list:
        if len(word) > 4:
            count+=1
    print(count)
    

['The', 'Learn', 'Python', 'Challenge', 'Casino.']
4
['They', 'bought', 'a', 'car']
1
['Casinoville']
1


In [409]:
#count the number of words in a list which is greater than a specific length
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
len_list=[]
for doc in doc_list:
    count=0
    print(doc.split())
    word_list = doc.split()
    for word in word_list:
        if len(word) > 4:
            count+=1
    len_list.append(count)
    print(count)
    #p=len_list.append(count)
    #print(len_list)
    

['The', 'Learn', 'Python', 'Challenge', 'Casino.']
4
['They', 'bought', 'a', 'car']
1
['Casinoville']
1


In [419]:
#count the number of words in a list which is greater than a specific length(4)
#and place the number in anew list
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
len_list=[]
for doc in doc_list:
    word_list=doc.split()
    #print(word)
    count=0
    for word in word_list:
        if len(word)>4:
            count+=1
    #print(count)
    len_list.append(count)
print(len_list)
    
        

[4, 1, 1]


In [448]:
#search a specific word in each doc name
#return the index of the original list
doc_list = ["The Learn python Challenge Casino.", "They a car", "Casinoville python"]
search = 'python'
list_index=[]
for doc in doc_list:
    #print(doc)
    word_list=doc.split()
    #print(word_list)
    #count=0
    for word in word_list:
        #print(word)
        if word == search:
            count=doc_list.index(doc)
            #print(count)
    list_index.append(count)
print(list_index)
            
    
    

['', '', '']


In [423]:
doc_list = ["The Learn python Challenge Casino.", "They python a car", "Casinoville python"]
doc_list.index("They python a car")

1

In [455]:
#search a specific word in each doc name
#return the index of the original list only if the word is present
doc_list = ["The Learn python Challenge Casino.", "They a python car", "Casinoville python"]
search = 'python'
list_index=[]
for doc in doc_list:
    word_list=doc.split()
    if search in word_list:
        index_doc=doc_list.index(doc)
        list_index.append(index_doc)
print(list_index)
    
    

[0, 1, 2]


In [464]:
#convert every word into lower case
#normalized = [token.rstrip('.,').lower() for token in tokens]
doc_list = ["The Learn python Challenge Casino.", "They python a car", "Casinoville python"]
#upper=[]
for doc in doc_list:
    word_list=doc.split()
    upper=[]
    for word in word_list:
        upper.append(word.rstrip('.,').lower())
    print(upper)

['the', 'learn', 'python', 'challenge', 'casino']
['they', 'python', 'a', 'car']
['casinoville', 'python']


In [470]:
doc_list = ["The Learn python Challenge Casino.", "They python a car", "Casinoville python"]
for doc in doc_list:
    list_nw=doc.split()
    normalized=[word.rstrip('no.,').upper() for word in list_nw]
    print(normalized)

['THE', 'LEAR', 'PYTH', 'CHALLENGE', 'CASI']
['THEY', 'PYTH', 'A', 'CAR']
['CASINOVILLE', 'PYTH']


In [ ]:
def multi_word_search(doc_list, keywords):
    """
    Takes list of documents (each document is a string) and a list of keywords.  
    Returns a dictionary where each key is a keyword, and the value is a list of indices
    (from doc_list) of the documents containing that keyword

    >>> doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
    >>> keywords = ['casino', 'they']
    >>> multi_word_search(doc_list, keywords)
    {'casino': [0, 1], 'they': [1]}
    """

In [ ]:
doc_list = ["The Learn python Challenge Casino.", "They python a car", "Casinoville python"]
keyword = ['casino', 'they']




In [475]:
def multi_keyword_search(doc_list,keyword):
    result={}
    for word in keyword:
        result[word]=word_search(doc_list,word)
    return result

In [474]:
eg_dict = {'one':1,
          'two':2,
          'three':3}
eg_dict['one']

1

In [492]:
mario = [
    {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3},
    {'name': 'Bowser', 'items': ['green shell',], 'finish': 1},
    # Sometimes the racer's name wasn't recorded
    {'name': None, 'items': ['mushroom',], 'finish': 2},
    {'name': 'Toad', 'items': ['green shell', 'mushroom'], 'finish': 1},
]
#mario = mario = [{'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3}]

In [493]:
print(mario[0])
print(mario[0]['items'])

{'name': 'Peach', 'items': ['green shell', 'banana', 'green shell'], 'finish': 3}
['green shell', 'banana', 'green shell']


In [500]:
count_dict={}
for row in mario:
    #print(row)
    if row['finish'] == 1:
        for elements in row['items']:
            #print(elements)
            if elements not in count_dict:
                count_dict[elements]=0
            count_dict[elements]+=1
print(count_dict)
    

{'green shell': 2, 'mushroom': 1}


In [508]:

def hand(hand_1):
    total = 0
    a = 0
    for i in hand_1:
        if i == 'K' or i == 'Q' or i == 'J' :
            total += 10
        elif i == 'A':
            a += 1
        else:
            total += int(i)  
    total+=a
    #print(total)
    while total+10 <= 21 and a > 0:
        total+=10
        #a-=1
    return total


In [513]:
hand_1 = ['A', '3', '2']
hand_2 = ['A','J','1']

In [510]:
hand(hand_1)

16

In [512]:
def blackjack_hand_greater_than(hand_1, hand_2):
    hand1=hand(hand_1)
    hand2=hand(hand_2)
    return hand1 <= 21 and (hand1 > hand2 or hand2 > 21)

In [515]:
blackjack_hand_greater_than(hand_1, hand_2)

True

In [ ]:
def hand(hand_1):
    total = 0
    a = 0
    for i in hand_1:
        if i == 'K' or i == 'Q' or i == 'J' :
            total += 10
        elif i == 'A':
            a += 1
        else:
            total += int(i)  
    total+=a
    #print(total)
    while total+10 <= 21 and a > 0:
        total+=10
        #a-=1
    return total
def blackjack_hand_greater_than(hand_1, hand_2):
    hand1=hand(hand_1)
    hand2=hand(hand_2)
    return hand1 <= 21 and (hand1 > hand2 or hand2 > 21)